name: Movie Picture Workflow

on: # Triggers for the workflow
  workflow_dispatch:  # Manual trigger using the workflow_dispatch event
  pull_request:  # Automatic trigger on pull request events targeting the main branch
    branches:
      - main
    paths:
      - 'starter/backend/**'
jobs:
  lint-and-test:
    name: Run Lint and Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        task: [lint, test]
    defaults:
      run:
        working-directory: starter/backend
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Lint or Test
        run: |
          if [ "${{ matrix.task }}" == "lint" ]; then
            flake8 .
          else
            pytest
          fi

  build:
    name: Build Backend Image
    needs: lint-and-test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: starter/backend
    steps:

    - name: Check out repository
      uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt


    - name: Build Docker Image
      run: docker build -t backend-app .
